"""empty message

Revision ID: 34743927cb7c
Revises: 
Create Date: 2019-06-10 01:10:05.274934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34743927cb7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moviename', sa.String(), nullable=True),
    sa.Column('releasedate', sa.Date(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('collection', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Profiles')
    op.drop_table('Movies')
    # ### end Alembic commands ###
