"""empty message

Revision ID: bc91881ff4f6
Revises: 
Create Date: 2019-06-11 00:03:45.864100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc91881ff4f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moviename', sa.String(), nullable=True),
    sa.Column('releasedate', sa.Date(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('collection', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profileid', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profileid'], ['Profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Directors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profileid', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profileid'], ['Profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Producers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profileid', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profileid'], ['Profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MovieActors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actorid', sa.Integer(), nullable=True),
    sa.Column('movieid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actorid'], ['Actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movieid'], ['Movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MovieDirectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('directorid', sa.Integer(), nullable=True),
    sa.Column('movieid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['directorid'], ['Directors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movieid'], ['Movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('MovieProducers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producerid', sa.Integer(), nullable=True),
    sa.Column('movieid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movieid'], ['Movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producerid'], ['Producers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MovieProducers')
    op.drop_table('MovieDirectors')
    op.drop_table('MovieActors')
    op.drop_table('Producers')
    op.drop_table('Directors')
    op.drop_table('Actors')
    op.drop_table('Profiles')
    op.drop_table('Movies')
    # ### end Alembic commands ###
